apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: argo-repo.kr.ncr.ntruss.com/apache:20251027-fc2eda4
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: web
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
    nodePort: 30080
